### ISSUE TITLE
extra spaces in disease_mapping file

### ISSUE THREAD

**Issue by wizardlancet** [chenxz1111/RareBench#1]
https://github.com/chenxz1111/RareBench/blob/8138a7459d7ae3d19e2d3469165519db4307a953/mapping/disease_mapping.json#L4434

In the disease_mapping file, on line 4434 and others, there are extra spaces after the quotation mark “.

**Comment by chenxz1111** [comment]
Thank you for pointing out the formatting issue in the `disease_mapping.json` file. We have corrected these issues and updated the repository accordingly.
